events {}

http {
    include       /etc/nginx/mime.types;   # <-- without this, .css is sent as octet-stream and the browser ignores it
    default_type  application/octet-stream;
    sendfile      on;
 
    # Docker's embedded DNS. Lets 'app' resolve at request time, so nginx
    # doesn't hard-crash if the app container restarts.
    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;
        server_name _;

        location /static/ {
            alias /var/www/static/;
            expires 30d;
            access_log off;
        }
        location / {
            proxy_pass http://app:5000;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }


    }
}